version: '3'

services:
  frontend:
    build:
      context: ./client-side
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client-side/.env
    volumes:
      - ./client-side/src:/src/src
    depends_on:
      - backend

  backend:
    build:
      context: ./server-side
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database
    env_file:
      - ./server-side/.env
    volumes:
      - ./server-side/src:/src/src

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
      - '5555:5555'
